name: orgtree

services:
  server:
    build:
      context: .
      target: server
    environment:
      SERVER_HOST: 0.0.0.0
      SERVER_PORT: ${SERVER_PORT:-3001}
      MUTATE_MIN_MS: ${MUTATE_MIN_MS:-3000}
      MUTATE_MAX_MS: ${MUTATE_MAX_MS:-5000}
    expose:
      - '${SERVER_PORT:-3001}'

  client:
    build:
      context: .
      target: client
    environment:
      SERVER_PORT: ${SERVER_PORT:-3001}
      NGINX_ENVSUBST_FILTER: SERVER_PORT
    ports:
      - '${CLIENT_PORT:-8080}:80'
    depends_on:
      - server
